export const GET_EVENT_REQUEST = 'GET_EVENT_REQUEST';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT_ERROR = 'GET_EVENT_ERROR';

export const GET_INFLUENCER_REQUEST = "GET_INFLUENCER_REQUEST";
export const GET_INFLUENCER_SUCCESS = "GET_INFLUENCER_SUCCESS";
export const GET_INFLUENCER_ERROR = "GET_INFLUENCER_ERROR";

export const GET_COMPANY_REQUEST = "GET_COMPANY_REQUEST";
export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS";
export const GET_COMPANY_ERROR =  "GET_COMPANY_ERROR";

export const GET_STATUS_REQUEST = "GET_STATUS_REQUEST";
export const GET_STATUS_SUCCESS = "GET_STATUS_SUCCESS";
export const GET_STATUS_ERROR = "GET_STATUS_ERROR";

export const POST_COMPANY_REQUEST = "POST_COMPANY_REQUEST";
export const POST_COMPANY_SUCCESS = "POST_COMPANY_SUCCESS";
export const POST_COMPANY_ERROR = "POST_COMPANY_ERROR";

export const POST_INFLUENCER_REQUEST = "POST_INFLUENCER_REQUEST";
export const POST_INFLUENCER_SUCCESS = "POST_INFLUENCER_SUCCESS";
export const POST_INFLUENCER_ERROR = "POST_INFLUENCER_ERROR";

export const CHECK_IN_REQUEST = "CHECK_IN_REQUEST";
export const CHECK_IN_SUCCESS = "CHECK_IN_SUCCESS";
export const CHECK_IN_ERROR = "CHECK_IN_ERROR";
export const CHECK_IN_FINALLY = "CHECK_IN_FINALLY";

export const FIND_INFLUENCER_SUCCESS = "FIND_INFLUENCER_SUCCESS";

// ----- by id difference -----
export const GET_INFLUENCER_ID_SUCCESS = "GET_INFLUENCER_ID_SUCCESS";
export const GET_EVENT_BY_ID_SUCCESS = "GET_EVENT_BY_ID_SUCCESS";
export const GET_COMPANY_EDIT_SUCCESS = "GET_COMPANY_EDIT_SUCCESS";
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";

// ----- showing msg ---------
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const SHOW_CREATE_EVENT = "SHOW_CREATE_EVENT";